package core;

public enum MessageCode {
    PROVER_SENDING_NEW_BLOCK,
    PROVER_REQUEST_FOR_CURRENT_BLOCKCHAIN,
    PROVER_SENDING_SERVER_PORT_NUMBER,
    END_OF_FILE,
    VERIFIER_CHECK_IS_FILE_STORED
}
